server:
  port: 9527

spring:
  application:
    name: oldmoon-zuul-9704

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/ #eureka的服务地址，可以用','隔开多个地址
  instance:
    instance-id: oldmoon-zuul-9704 #eureka中显示的名称
    prefer-ip-address: true #显示ip

info: #服务信息，可在eureka中显示
  app.name: oldmoon-zuul-9704
  company.name: oldmoon.top
  build.artifactId: oldmoon-zuul-9704
  build.version: 1.0-SNAPSHOT

